version: '3.8'
volumes:
  postgres_data: {}

services:
  web:
    build:
      context: ./audio_book
      dockerfile: ./audio_book/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./audio_book/:/app/
    ports:
      - "8000:8000"
    env_file:
      - .envs/.local/.postgres
      - .envs/.local/.django
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_dev

