version: '3.8'

volumes:
  postgres_data: { }
  static_volume: { }
  media_volume: { }

services:
  postgres:
    build:
      context: ./audio_book
      dockerfile: ./compose/postgres/Dockerfile
    image: audio_book_production_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.prod/.postgres

  django:
    build:
      context: ./audio_book
      dockerfile: compose/Dockerfile.prod

    image: audio_book_production_django

    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles

    env_file:
      - .envs/.prod/.django
      - .envs/.prod/.postgres
    depends_on:
      - postgres
    command: /start

  
  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - django
