version: '3.8'

volumes:
  postgres_data: { }
  static_volume: { }
  media_volume: { }

services:
  db:
    image: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .envs/.prod/.postgres

  web:
    build:
      context: ./audio_book
      dockerfile: ./compose/Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./audio_book/:/home/audio_book_server/web
      - media_volume:/home/audio_book_server/media
      - static_volume:/home/audio_book_server/web/staticfiles
    expose:
      - 8000
    env_file:
      - .envs/.prod/.django
      - .envs/.prod/.postgres
    depends_on:
      - db
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/audio_book/web/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web
